{{-- generated by command php artisan make:view cruds/index --}}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crud List</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table, th, td {
            border: 1px solid #ddd;
        }

        th, td {
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>

    <h2>Crud List</h2>

    <a href="{{ route('cruds.create') }}">Add New</a>

    @if(count($cruds) > 0)
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Text</th>
                    <th>Email</th>
                    <th>Date</th>
                    <th>Decimal</th>
                    <th>Integer</th>
                    <th>Datetime</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @php $count = 0 @endphp
                @foreach ($cruds as $crud)
                    @php
                        $count++;
                        $carbonDate = \Carbon\Carbon::parse($crud->date);
                        $formattedDate = $carbonDate->format('d-m-Y');
                        $carbonDateTime = \Carbon\Carbon::parse($crud->datetime);
                        $formattedDateTime = $carbonDateTime->format('d-m-Y H:i A');
                    @endphp
                    <tr>
                        <td>{{ $count }}</td>
                        <td><a href="{{ route('cruds.show', $crud->id) }}">{{ $crud->text }}</a></td>
                        <td>{{ $crud->email }}</td>
                        <td>{{ $formattedDate }}</td>
                        <td>{{ $crud->decimal }}</td>
                        <td>{{ $crud->integer }}</td>
                        <td>{{ $formattedDateTime}}</td>
                        <td>
                            <a href="{{ route('cruds.edit', $crud->id) }}">Update</a>

                            <form action="{{ route('cruds.destroy', $crud->id) }}" method="POST">
                                @csrf
                                @method('delete')
                                <button type="submit">Delete</button>
                            </form>

                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p>No record available.</p>
    @endif

</body>
</html>
